modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="simplepoweredequipment" #mandatory
version="${version}" #mandatory
displayName="Simple Powered Equipment" #mandatory
#updateJSONURL="" #optional
#displayURL="" #optional
#logoFile="" #optional
#credits="" #optional
#authors="" #optional
description='''
Add RF powered tools and armour, that drain power instead of durability.
'''